/* ============================================================
   CONFIG — STATIC DATA
   Ordre et noms FR exacts d'après les checklists pokecardex PDF
============================================================ */

/** Pokecardex CDN image — visuels JP officiels */
const getPokecardexUrl = (setCode, pos) =>
  `https://pokecardex-scans.b-cdn.net/sets_jp/${setCode}/${pos}.jpg?class=md`;

/** Pokémon sprite — pixel art Gen 1 pour #1-151, standard pour les suivants */
const getSpriteUrl = (dexId) =>
  dexId <= 151
    ? `https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-i/red-blue/transparent/${dexId}.png`
    : `https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/${dexId}.png`;

/** PokeAPI item sprite (fallback trainers) */
const getItemSpriteUrl = (slug) =>
  `https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/${slug}.png`;

/** TCGdex set ID (pour modal flip EN) */
const TCGDEX_SET = { base: 'base1', jungle: 'base2', fossil: 'base3', rocket: 'base5' };

const UI_LABELS = {
  fr: { owned: 'POSSEDEES', total: 'TOTAL', complete: 'COMPLET', all: 'TOUTES', yes: 'POSSEDEES', no: 'MANQUANTES', search: '🔍 Rechercher...', subtitle: 'TRACKER — EDITION JAPONAISE',
        export: 'EXPORTER', import: 'IMPORTER', reset: 'RESET',
        noCards: '⚠️ Aucune carte à exporter !', alreadyEmpty: '⚠️ La collection est déjà vide !',
        imported: 'cartes importées !', resetDone: '🗑 Collection réinitialisée',
        resetTitle: 'REMETTRE', resetCards: 'CARTES À ZÉRO ?', resetHint: 'Cette action est irréversible.\nPense à exporter avant !',
        resetYes: 'OUI, RESET', resetNo: 'ANNULER',
        extrasTab: 'EXTRAS', extrasAdd: 'AJOUTER', extrasName: 'Nom de la carte', extrasType: 'Type', extrasDex: 'N° Pokédex (optionnel)', extrasEmpty: 'Aucune carte extra. Ajoute-en une !', extrasDelete: 'Supprimer', extrasEdit: 'Modifier', extrasSave: 'MODIFIER', extrasCancel: 'ANNULER', extrasEditing: 'ÉDITION', extrasPokemonSearch: 'CHERCHER POKÉMON', extrasPokemonPlaceholder: 'Ex: Pikachu, Charizard...', sortDefault: 'DÉFAUT', sortName: 'NOM', sortType: 'TYPE', showcase: 'SHOWCASE', lock: 'VERROUILLER', unlock: 'DÉVERROUILLER' },
  en: { owned: 'OWNED', total: 'TOTAL', complete: 'COMPLETE', all: 'ALL', yes: 'OWNED', no: 'MISSING', search: '🔍 Search...', subtitle: 'TRACKER — JAPANESE EDITION',
        export: 'EXPORT', import: 'IMPORT', reset: 'RESET',
        noCards: '⚠️ No cards to export!', alreadyEmpty: '⚠️ Collection is already empty!',
        imported: 'cards imported!', resetDone: '🗑 Collection reset',
        resetTitle: 'RESET', resetCards: 'CARDS?', resetHint: 'This cannot be undone.\nExport first just in case!',
        resetYes: 'YES, RESET', resetNo: 'CANCEL',
        extrasTab: 'EXTRAS', extrasAdd: 'ADD', extrasName: 'Card name', extrasType: 'Type', extrasDex: 'Pokédex # (optional)', extrasEmpty: 'No extra cards yet. Add one!', extrasDelete: 'Delete', extrasEdit: 'Edit', extrasSave: 'SAVE', extrasCancel: 'CANCEL', extrasEditing: 'EDITING', extrasPokemonSearch: 'SEARCH POKÉMON', extrasPokemonPlaceholder: 'Ex: Pikachu, Charizard...', sortDefault: 'DEFAULT', sortName: 'NAME', sortType: 'TYPE', showcase: 'SHOWCASE', lock: 'LOCK', unlock: 'UNLOCK' },
  jp: { owned: '所持済み', total: '合計', complete: '完成度', all: '全て', yes: '所持済み', no: '未所持', search: '🔍 検索...', subtitle: 'トラッカー — 日本語版',
        export: 'エクスポート', import: 'インポート', reset: 'リセット',
        noCards: '⚠️ エクスポートするカードがありません！', alreadyEmpty: '⚠️ コレクションはすでに空です！',
        imported: '枚のカードをインポートしました！', resetDone: '🗑 コレクションをリセットしました',
        resetTitle: 'リセット', resetCards: '枚をリセット？', resetHint: 'この操作は取り消せません。\n先にエクスポートしてください！',
        resetYes: 'リセット', resetNo: 'キャンセル',
        extrasTab: 'EXTRAS', extrasAdd: '追加', extrasName: 'カード名', extrasType: 'タイプ', extrasDex: '図鑑番号（任意）', extrasEmpty: 'エクストラカードがありません', extrasDelete: '削除', extrasEdit: '編集', extrasSave: '保存', extrasCancel: 'キャンセル', extrasEditing: '編集中', extrasPokemonSearch: 'ポケモン検索', extrasPokemonPlaceholder: '例: Pikachu...', sortDefault: 'デフォルト', sortName: '名前', sortType: 'タイプ', showcase: 'ショーケース', lock: 'ロック', unlock: 'ロック解除' },
};

const RARITY_LABELS = {
  fr: { holo: '★★★ HOLO RARE', rare: '★★ RARE', uncommon: '★ PEU COMMUNE', common: '◆ COMMUNE' },
  en: { holo: '★★★ HOLO RARE', rare: '★★ RARE', uncommon: '★ UNCOMMON',    common: '◆ COMMON'  },
  jp: { holo: '★★★ キラレア',   rare: '★★ レア',  uncommon: '★ アンコモン',  common: '◆ コモン'  },
};

/**
 * SETS — ordre exact des checklists pokecardex PDF
 * img  = position sur pokecardex = numéro dans l'URL CDN
 * n    = clé unique stable pour localStorage
 * r    = rareté (d'après les symboles PDF : ● common, ◆ uncommon, ★ rare, ☆ holo)
 * d    = numéro pokédex (sprite fallback + description)
 * item = slug item PokeAPI (fallback trainers/énergies)
 */
const SETS = {

  /* ================================================================
     OR1 — EXPANSION PACK — 拡張パック 1996
     102 cartes — ordre exact checklist pokecardex
  ================================================================ */
  base: {
    name: { fr: 'SET DE BASE', en: 'BASE SET', jp: '拡張パック' },
    subtitle: '拡張パック 1996',
    cdnSet: 'OR1',
    cards: [
      { n:'b01',  img:1,   jp:'フシギダネ',         fr:'Bulbizarre',                   en:'Bulbasaur',              r:'common',   t:'🌿', d:1   },
      { n:'b02',  img:2,   jp:'フシギソウ',         fr:'Herbizarre',                   en:'Ivysaur',                r:'uncommon', t:'🌿', d:2   },
      { n:'b03',  img:3,   jp:'フシギバナ',         fr:'Florizarre',                   en:'Venusaur',               r:'holo',     t:'🌿', d:3   },
      { n:'b04',  img:4,   jp:'キャタピー',         fr:'Chenipan',                     en:'Caterpie',               r:'common',   t:'🐛', d:10  },
      { n:'b05',  img:5,   jp:'トランセル',         fr:'Chrysacier',                   en:'Metapod',                r:'common',   t:'🐛', d:11  },
      { n:'b06',  img:6,   jp:'ビードル',           fr:'Aspicot',                      en:'Weedle',                 r:'common',   t:'🐛', d:13  },
      { n:'b07',  img:7,   jp:'コクーン',           fr:'Coconfort',                    en:'Kakuna',                 r:'uncommon', t:'🐛', d:14  },
      { n:'b08',  img:8,   jp:'スピアー',           fr:'Dardargnan',                   en:'Beedrill',               r:'rare',     t:'🐛', d:15  },
      { n:'b09',  img:9,   jp:'ニドラン♂',         fr:'Nidoran ♂',                   en:'Nidoran♂',              r:'common',   t:'💜', d:32  },
      { n:'b10',  img:10,  jp:'ニドリーノ',         fr:'Nidorino',                     en:'Nidorino',               r:'uncommon', t:'💜', d:33  },
      { n:'b11',  img:11,  jp:'ニドキング',         fr:'Nidoking',                     en:'Nidoking',               r:'holo',     t:'💜', d:34  },
      { n:'b12',  img:12,  jp:'ドガース',           fr:'Smogo',                        en:'Koffing',                r:'common',   t:'☁️', d:109 },
      { n:'b13',  img:13,  jp:'モンジャラ',         fr:'Saquedeneu',                   en:'Tangela',                r:'common',   t:'🌿', d:114 },
      { n:'b14',  img:14,  jp:'ヒトカゲ',           fr:'Salamèche',                    en:'Charmander',             r:'common',   t:'🔥', d:4   },
      { n:'b15',  img:15,  jp:'リザード',           fr:'Reptincel',                    en:'Charmeleon',             r:'uncommon', t:'🔥', d:5   },
      { n:'b16',  img:16,  jp:'リザードン',         fr:'Dracaufeu',                    en:'Charizard',              r:'holo',     t:'🔥', d:6   },
      { n:'b17',  img:17,  jp:'ロコン',             fr:'Goupix',                       en:'Vulpix',                 r:'common',   t:'🔥', d:37  },
      { n:'b18',  img:18,  jp:'キュウコン',         fr:'Feunard',                      en:'Ninetales',              r:'holo',     t:'🔥', d:38  },
      { n:'b19',  img:19,  jp:'ガーディ',           fr:'Caninos',                      en:'Growlithe',              r:'uncommon', t:'🔥', d:58  },
      { n:'b20',  img:20,  jp:'ウインディ',         fr:'Arcanin',                      en:'Arcanine',               r:'uncommon', t:'🔥', d:59  },
      { n:'b21',  img:21,  jp:'ポニータ',           fr:'Ponyta',                       en:'Ponyta',                 r:'common',   t:'🔥', d:77  },
      { n:'b22',  img:22,  jp:'マグマラシ',         fr:'Magmar',                       en:'Magmar',                 r:'uncommon', t:'🔥', d:126 },
      { n:'b23',  img:23,  jp:'ゼニガメ',           fr:'Carapuce',                     en:'Squirtle',               r:'common',   t:'💧', d:7   },
      { n:'b24',  img:24,  jp:'カメール',           fr:'Carabaffe',                    en:'Wartortle',              r:'uncommon', t:'💧', d:8   },
      { n:'b25',  img:25,  jp:'カメックス',         fr:'Tortank',                      en:'Blastoise',              r:'holo',     t:'💧', d:9   },
      { n:'b26',  img:26,  jp:'ニョロモ',           fr:'Ptitard',                      en:'Poliwag',                r:'common',   t:'💧', d:60  },
      { n:'b27',  img:27,  jp:'ニョロゾ',           fr:'Têtarte',                      en:'Poliwhirl',              r:'uncommon', t:'💧', d:61  },
      { n:'b28',  img:28,  jp:'ニョロボン',         fr:'Tartard',                      en:'Poliwrath',              r:'holo',     t:'💧', d:62  },
      { n:'b29',  img:29,  jp:'タマザラシ',         fr:'Otaria',                       en:'Seel',                   r:'uncommon', t:'💧', d:86  },
      { n:'b30',  img:30,  jp:'ジュゴン',           fr:'Lamantine',                    en:'Dewgong',                r:'rare',     t:'💧', d:87  },
      { n:'b31',  img:31,  jp:'ヒトデマン',         fr:'Stari',                        en:'Staryu',                 r:'common',   t:'💧', d:120 },
      { n:'b32',  img:32,  jp:'スターミー',         fr:'Staross',                      en:'Starmie',                r:'uncommon', t:'💧', d:121 },
      { n:'b33',  img:33,  jp:'コイキング',         fr:'Magicarpe',                    en:'Magikarp',               r:'common',   t:'💧', d:129 },
      { n:'b34',  img:34,  jp:'ギャラドス',         fr:'Léviator',                     en:'Gyarados',               r:'holo',     t:'💧', d:130 },
      { n:'b35',  img:35,  jp:'ピカチュウ',         fr:'Pikachu',                      en:'Pikachu',                r:'common',   t:'⚡', d:25  },
      { n:'b36',  img:36,  jp:'ライチュウ',         fr:'Raichu',                       en:'Raichu',                 r:'holo',     t:'⚡', d:26  },
      { n:'b37',  img:37,  jp:'コイル',             fr:'Magnéti',                      en:'Magnemite',              r:'common',   t:'⚡', d:81  },
      { n:'b38',  img:38,  jp:'レアコイル',         fr:'Magneton',                     en:'Magneton',               r:'holo',     t:'⚡', d:82  },
      { n:'b39',  img:39,  jp:'ビリリダマ',         fr:'Voltorbe',                     en:'Voltorb',                r:'common',   t:'⚡', d:100 },
      { n:'b40',  img:40,  jp:'マルマイン',         fr:'Électrode',                    en:'Electrode',              r:'rare',     t:'⚡', d:101 },
      { n:'b41',  img:41,  jp:'エレブー',           fr:'Elektek',                      en:'Electabuzz',             r:'rare',     t:'⚡', d:125 },
      { n:'b42',  img:42,  jp:'ザップドス',         fr:'Electhor',                     en:'Zapdos',                 r:'holo',     t:'⚡', d:145 },
      { n:'b43',  img:43,  jp:'ケーシィ',           fr:'Abra',                         en:'Abra',                   r:'common',   t:'🔮', d:63  },
      { n:'b44',  img:44,  jp:'フーディン',         fr:'Kadabra',                      en:'Kadabra',                r:'uncommon', t:'🔮', d:64  },
      { n:'b45',  img:45,  jp:'アラカザム',         fr:'Alakazam',                     en:'Alakazam',               r:'holo',     t:'🔮', d:65  },
      { n:'b46',  img:46,  jp:'ゴース',             fr:'Fantominus',                   en:'Gastly',                 r:'common',   t:'👻', d:92  },
      { n:'b47',  img:47,  jp:'ゴースト',           fr:'Spectrum',                     en:'Haunter',                r:'uncommon', t:'👻', d:93  },
      { n:'b48',  img:48,  jp:'スリープ',           fr:'Soporifik',                    en:'Drowzee',                r:'common',   t:'🔮', d:96  },
      { n:'b49',  img:49,  jp:'ルージュラ',         fr:'Lippoutou',                    en:'Jynx',                   r:'uncommon', t:'❄️', d:124 },
      { n:'b50',  img:50,  jp:'ミュウツー',         fr:'Mewtwo',                       en:'Mewtwo',                 r:'holo',     t:'🔮', d:150 },
      { n:'b51',  img:51,  jp:'サンド',             fr:'Sabelette',                    en:'Sandshrew',              r:'common',   t:'💀', d:27  },
      { n:'b52',  img:52,  jp:'ディグダ',           fr:'Taupiqueur',                   en:'Diglett',                r:'common',   t:'💀', d:50  },
      { n:'b53',  img:53,  jp:'ダグトリオ',         fr:'Triopikeur',                   en:'Dugtrio',                r:'rare',     t:'💀', d:51  },
      { n:'b54',  img:54,  jp:'ワンリキー',         fr:'Machoc',                       en:'Machop',                 r:'common',   t:'👊', d:66  },
      { n:'b55',  img:55,  jp:'ゴーリキー',         fr:'Machopeur',                    en:'Machoke',                r:'uncommon', t:'👊', d:67  },
      { n:'b56',  img:56,  jp:'カイリキー',         fr:'Mackogneur',                   en:'Machamp',                r:'holo',     t:'👊', d:68  },
      { n:'b57',  img:57,  jp:'イワーク',           fr:'Onix',                         en:'Onix',                   r:'uncommon', t:'🪨', d:95  },
      { n:'b58',  img:58,  jp:'エビワラー',         fr:'Tygnon',                       en:'Hitmonchan',             r:'holo',     t:'👊', d:107 },
      { n:'b59',  img:59,  jp:'ポッポ',             fr:'Roucool',                      en:'Pidgey',                 r:'common',   t:'🐦', d:16  },
      { n:'b60',  img:60,  jp:'ピジョン',           fr:'Roucoups',                     en:'Pidgeotto',              r:'uncommon', t:'🐦', d:17  },
      { n:'b61',  img:61,  jp:'コラッタ',           fr:'Rattata',                      en:'Rattata',                r:'common',   t:'⬛', d:19  },
      { n:'b62',  img:62,  jp:'ラッタ',             fr:'Rattatac',                     en:'Raticate',               r:'uncommon', t:'⬛', d:20  },
      { n:'b63',  img:63,  jp:'ピクシー',           fr:'Mélofée',                      en:'Clefairy',               r:'holo',     t:'✨', d:35  },
      { n:'b64',  img:64,  jp:'カモネギ',           fr:'Canarticho',                   en:"Farfetch'd",             r:'uncommon', t:'🐦', d:83  },
      { n:'b65',  img:65,  jp:'ドードー',           fr:'Doduo',                        en:'Doduo',                  r:'common',   t:'🐦', d:84  },
      { n:'b66',  img:66,  jp:'ラッキー',           fr:'Leveinard',                    en:'Chansey',                r:'holo',     t:'✨', d:113 },
      { n:'b67',  img:67,  jp:'ポリゴン',           fr:'Porygon',                      en:'Porygon',                r:'uncommon', t:'💻', d:137 },
      { n:'b68',  img:68,  jp:'ミニリュウ',         fr:'Minidraco',                    en:'Dratini',                r:'uncommon', t:'🐉', d:147 },
      { n:'b69',  img:69,  jp:'ハクリュー',         fr:'Draco',                        en:'Dragonair',              r:'rare',     t:'🐉', d:148 },
      // ── Trainers ──
      { n:'b70',  img:70,  jp:'エネルギー回収',         fr:"Suppression d'Énergie",         en:'Energy Removal',         r:'common',   t:'🃏', item:'energy-powder'  },
      { n:'b71',  img:71,  jp:'きずぐすり',              fr:'Potion',                        en:'Potion',                 r:'common',   t:'🃏', item:'potion'         },
      { n:'b72',  img:72,  jp:'ぼうふう',                fr:'Rafale de vent',                en:'Gust of Wind',           r:'common',   t:'🃏', item:'air-balloon'    },
      { n:'b73',  img:73,  jp:'いれかえ',                fr:'Échange',                       en:'Switch',                 r:'common',   t:'🃏', item:'escape-rope'    },
      { n:'b74',  img:74,  jp:'マサキ',                  fr:'Léo',                           en:'Bill',                   r:'common',   t:'🃏', item:'big-nugget'     },
      { n:'b75',  img:75,  jp:'いいきずぐすり',          fr:'Super Potion',                  en:'Super Potion',           r:'uncommon', t:'🃏', item:'super-potion'   },
      { n:'b76',  img:76,  jp:'エネルギーリムーブ',      fr:"Récupération d'Énergie",        en:'Energy Retrieval',       r:'uncommon', t:'🃏', item:'ether'          },
      { n:'b77',  img:77,  jp:'オーキド博士',             fr:'Professeur Chen',               en:'Professor Oak',          r:'uncommon', t:'🃏', item:'big-nugget'     },
      { n:'b78',  img:78,  jp:'きのみ',                  fr:'Rappel',                        en:'Revive',                 r:'uncommon', t:'🃏', item:'oran-berry'     },
      { n:'b79',  img:79,  jp:'ディフェンダー',          fr:'Defender',                      en:'Defender',               r:'uncommon', t:'🃏', item:'rocky-helmet'   },
      { n:'b80',  img:80,  jp:'まんたんのくすり',        fr:'Total Soin',                    en:'Full Heal',              r:'uncommon', t:'🃏', item:'full-heal'      },
      { n:'b81',  img:81,  jp:'プラスパワー',             fr:'PlusPower',                     en:'PlusPower',              r:'uncommon', t:'🃏', item:'x-attack'       },
      { n:'b82',  img:82,  jp:'ポケモン図鑑',            fr:'Pokédex',                       en:'Pokedex',                r:'uncommon', t:'🃏', item:'poke-doll'      },
      { n:'b83',  img:83,  jp:'ポケモンセンター',        fr:'Centre Pokémon',                en:'Pokemon Center',         r:'rare',     t:'🃏', item:'max-potion'     },
      { n:'b84',  img:84,  jp:'ポケモンフルート',        fr:'Flûte Pokémon',                 en:'Pokemon Flute',          r:'rare',     t:'🃏', item:'poke-flute'     },
      { n:'b85',  img:85,  jp:'メンテナンス',             fr:'Entretien',                     en:'Maintenance',            r:'rare',     t:'🃏', item:'poke-doll'      },
      { n:'b86',  img:86,  jp:'退化スプレー',             fr:'Spray Dés-évoluant',            en:'Devolution Spray',       r:'rare',     t:'🃏', item:'red-flute'      },
      { n:'b87',  img:87,  jp:'ポケモンあつめ',          fr:'Récupérateur',                  en:'Item Finder',            r:'rare',     t:'🃏', item:'amulet-coin'    },
      { n:'b88',  img:88,  jp:'スーパーエネルギー回収',  fr:"Double Suppression d'Énergie",  en:'Super Energy Removal',   r:'rare',     t:'🃏', item:'energy-powder'  },
      { n:'b89',  img:89,  jp:'ニセオーキド博士',        fr:'Faux Professeur Chen',          en:'Impostor Professor Oak', r:'rare',     t:'🃏', item:'dusk-stone'     },
      { n:'b90',  img:90,  jp:'コンピューターサーチ',    fr:'Recherche Informatique',        en:'Computer Search',        r:'rare',     t:'🃏', item:'poke-doll'      },
      { n:'b91',  img:91,  jp:'ピッピにんぎょう',        fr:'Peluche Mélofée',               en:'Clefairy Doll',          r:'rare',     t:'🃏', item:'poke-doll'      },
      { n:'b92',  img:92,  jp:'ポケモンあつめ②',        fr:'Rappel',                        en:'Scoop Up',               r:'rare',     t:'🃏', item:'super-rod'      },
      { n:'b93',  img:93,  jp:'ポケモントレーダー',      fr:'Marchand de Pokémon',           en:'Pokemon Trader',         r:'rare',     t:'🃏', item:'amulet-coin'    },
      { n:'b94',  img:94,  jp:'ポケモンブリーダー',      fr:'Eleveur de Pokémon',            en:'Pokemon Breeder',        r:'rare',     t:'🃏', item:'oval-stone'     },
      { n:'b95',  img:95,  jp:'わるいたくらみ',          fr:'Fillette',                      en:'Lass',                   r:'rare',     t:'🃏', item:'dusk-stone'     },
      { n:'b96',  img:96,  jp:'無色エネルギー',          fr:'Double Énergie Incolore',       en:'Double Colorless Energy',r:'uncommon', t:'⭐', item:'star-piece'    },
    ],
  },

  /* ================================================================
     OR2 — POKÉMON JUNGLE — ポケモンジャングル 1997
     48 cartes — ordre exact checklist pokecardex
  ================================================================ */
  jungle: {
    name: { fr: 'JUNGLE', en: 'JUNGLE', jp: 'ポケモンジャングル' },
    subtitle: 'ポケモンジャングル 1997',
    cdnSet: 'OR2',
    cards: [
      { n:'j01', img:1,  jp:'バタフリー',   fr:'Papilusion',   en:'Butterfree',   r:'uncommon', t:'🐛', d:12  },
      { n:'j02', img:2,  jp:'ニドラン♀',   fr:'Nidoran ♀',   en:'Nidoran♀',    r:'common',   t:'💜', d:29  },
      { n:'j03', img:3,  jp:'ニドリーナ',   fr:'Nidorina',     en:'Nidorina',     r:'uncommon', t:'💜', d:30  },
      { n:'j04', img:4,  jp:'ニドクイン',   fr:'Nidoqueen',    en:'Nidoqueen',    r:'holo',     t:'💜', d:31  },
      { n:'j05', img:5,  jp:'ナゾノクサ',   fr:'Mystherbe',    en:'Oddish',       r:'common',   t:'🌿', d:43  },
      { n:'j06', img:6,  jp:'クサイハナ',   fr:'Ortide',       en:'Gloom',        r:'uncommon', t:'🌿', d:44  },
      { n:'j07', img:7,  jp:'ラフレシア',   fr:'Rafflesia',    en:'Vileplume',    r:'holo',     t:'🌸', d:45  },
      { n:'j08', img:8,  jp:'パラス',       fr:'Paras',        en:'Paras',        r:'common',   t:'🌿', d:46  },
      { n:'j09', img:9,  jp:'パラセクト',   fr:'Parasect',     en:'Parasect',     r:'uncommon', t:'🌿', d:47  },
      { n:'j10', img:10, jp:'コンパン',     fr:'Mimitoss',     en:'Venonat',      r:'common',   t:'🐛', d:48  },
      { n:'j11', img:11, jp:'モルフォン',   fr:'Aéromite',     en:'Venomoth',     r:'holo',     t:'🐛', d:49  },
      { n:'j12', img:12, jp:'マダツボミ',   fr:'Chétiflor',    en:'Bellsprout',   r:'common',   t:'🌿', d:69  },
      { n:'j13', img:13, jp:'ウツドン',     fr:'Boustiflor',   en:'Weepinbell',   r:'uncommon', t:'🌿', d:70  },
      { n:'j14', img:14, jp:'ウツボット',   fr:'Empiflor',     en:'Victreebel',   r:'holo',     t:'🌿', d:71  },
      { n:'j15', img:15, jp:'タマタマ',     fr:'Noeunoeuf',    en:'Exeggcute',    r:'common',   t:'🌿', d:102 },
      { n:'j16', img:16, jp:'ナッシー',     fr:'Noadkoko',     en:'Exeggutor',    r:'uncommon', t:'🌿', d:103 },
      { n:'j17', img:17, jp:'ストライク',   fr:'Insécateur',   en:'Scyther',      r:'holo',     t:'🌿', d:123 },
      { n:'j18', img:18, jp:'カイロス',     fr:'Scarabrute',   en:'Pinsir',       r:'holo',     t:'🌿', d:127 },
      { n:'j19', img:19, jp:'ギャロップ',   fr:'Galopa',       en:'Rapidash',     r:'uncommon', t:'🔥', d:78  },
      { n:'j20', img:20, jp:'ブースター',   fr:'Pyroli',       en:'Flareon',      r:'holo',     t:'🔥', d:136 },
      { n:'j21', img:21, jp:'トサキント',   fr:'Poissirène',   en:'Goldeen',      r:'common',   t:'💧', d:118 },
      { n:'j22', img:22, jp:'アズマオウ',   fr:'Poissoroy',    en:'Seaking',      r:'uncommon', t:'💧', d:119 },
      { n:'j23', img:23, jp:'シャワーズ',   fr:'Aquali',       en:'Vaporeon',     r:'holo',     t:'💧', d:134 },
      { n:'j24', img:24, jp:'ピカチュウ',   fr:'Pikachu',      en:'Pikachu',      r:'common',   t:'⚡', d:25  },
      { n:'j25', img:25, jp:'マルマイン',   fr:'Électrode',    en:'Electrode',    r:'holo',     t:'⚡', d:101 },
      { n:'j26', img:26, jp:'サンダース',   fr:'Voltali',      en:'Jolteon',      r:'holo',     t:'⚡', d:135 },
      { n:'j27', img:27, jp:'バリヤード',   fr:'M. Mime',      en:'Mr. Mime',     r:'holo',     t:'🔮', d:122 },
      { n:'j28', img:28, jp:'マンキー',     fr:'Férosinge',    en:'Mankey',       r:'common',   t:'👊', d:56  },
      { n:'j29', img:29, jp:'オコリザル',   fr:'Colossinge',   en:'Primeape',     r:'uncommon', t:'👊', d:57  },
      { n:'j30', img:30, jp:'カラカラ',     fr:'Osselait',     en:'Cubone',       r:'common',   t:'💀', d:104 },
      { n:'j31', img:31, jp:'ガラガラ',     fr:'Ossatueur',    en:'Marowak',      r:'uncommon', t:'💀', d:105 },
      { n:'j32', img:32, jp:'サイホーン',   fr:'Rhinocorne',   en:'Rhyhorn',      r:'common',   t:'🪨', d:111 },
      { n:'j33', img:33, jp:'サイドン',     fr:'Rhinoféros',   en:'Rhydon',       r:'uncommon', t:'🪨', d:112 },
      { n:'j34', img:34, jp:'ピジョット',   fr:'Roucarnage',   en:'Pidgeot',      r:'holo',     t:'🐦', d:18  },
      { n:'j35', img:35, jp:'オニスズメ',   fr:'Piafabec',     en:'Spearow',      r:'common',   t:'🐦', d:21  },
      { n:'j36', img:36, jp:'オニドリル',   fr:'Rapasdepic',   en:'Fearow',       r:'uncommon', t:'🐦', d:22  },
      { n:'j37', img:37, jp:'ピクシー',     fr:'Mélodelfe',    en:'Clefable',     r:'holo',     t:'✨', d:36  },
      { n:'j38', img:38, jp:'プリン',       fr:'Rondoudou',    en:'Jigglypuff',   r:'common',   t:'✨', d:39  },
      { n:'j39', img:39, jp:'プクリン',     fr:'Grodoudou',    en:'Wigglytuff',   r:'holo',     t:'✨', d:40  },
      { n:'j40', img:40, jp:'ニャース',     fr:'Miaouss',      en:'Meowth',       r:'common',   t:'⬛', d:52  },
      { n:'j41', img:41, jp:'ペルシアン',   fr:'Persian',      en:'Persian',      r:'uncommon', t:'⬛', d:53  },
      { n:'j42', img:42, jp:'ドードリオ',   fr:'Dodrio',       en:'Dodrio',       r:'uncommon', t:'🐦', d:85  },
      { n:'j43', img:43, jp:'ベロリンガ',   fr:'Excelangue',   en:'Lickitung',    r:'uncommon', t:'⬛', d:108 },
      { n:'j44', img:44, jp:'ガルーラ',     fr:'Kangourex',    en:'Kangaskhan',   r:'holo',     t:'🦘', d:115 },
      { n:'j45', img:45, jp:'ケンタロス',   fr:'Tauros',       en:'Tauros',       r:'uncommon', t:'⬛', d:128 },
      { n:'j46', img:46, jp:'イーブイ',     fr:'Evoli',        en:'Eevee',        r:'common',   t:'⬛', d:133 },
      { n:'j47', img:47, jp:'カビゴン',     fr:'Ronflex',      en:'Snorlax',      r:'holo',     t:'⬛', d:143 },
      { n:'j48', img:48, jp:'モンスターボール', fr:'Poké Ball', en:'Poké Ball',   r:'common',   t:'🃏', item:'poke-ball' },
    ],
  },

  /* ================================================================
     OR3 — MYSTERY OF THE FOSSILS — 化石の秘密 1997
     48 cartes — ordre exact checklist pokecardex
  ================================================================ */
  fossil: {
    name: { fr: 'FOSSIL', en: 'FOSSIL', jp: '化石の秘密' },
    subtitle: '化石の秘密 1997',
    cdnSet: 'OR3',
    cards: [
      { n:'f01', img:1,  jp:'アーボ',       fr:'Abo',           en:'Ekans',        r:'common',   t:'☁️', d:23  },
      { n:'f02', img:2,  jp:'アーボック',   fr:'Arbok',         en:'Arbok',        r:'uncommon', t:'☁️', d:24  },
      { n:'f03', img:3,  jp:'ズバット',     fr:'Nosferapti',    en:'Zubat',        r:'common',   t:'☁️', d:41  },
      { n:'f04', img:4,  jp:'ゴルバット',   fr:'Nosferalto',    en:'Golbat',       r:'uncommon', t:'☁️', d:42  },
      { n:'f05', img:5,  jp:'ベトベター',   fr:'Tadmorv',       en:'Grimer',       r:'common',   t:'☁️', d:88  },
      { n:'f06', img:6,  jp:'ベトベトン',   fr:'Grotadmorv',    en:'Muk',          r:'holo',     t:'☁️', d:89  },
      { n:'f07', img:7,  jp:'マタドガス',   fr:'Smogogo',       en:'Weezing',      r:'uncommon', t:'☁️', d:110 },
      { n:'f08', img:8,  jp:'マグマラシ',   fr:'Magmar',        en:'Magmar',       r:'uncommon', t:'🔥', d:126 },
      { n:'f09', img:9,  jp:'ファイヤー',   fr:'Sulfura',       en:'Moltres',      r:'holo',     t:'🔥', d:146 },
      { n:'f10', img:10, jp:'コダック',     fr:'Psykokwak',     en:'Psyduck',      r:'common',   t:'💧', d:54  },
      { n:'f11', img:11, jp:'ゴルダック',   fr:'Akwakwak',      en:'Golduck',      r:'uncommon', t:'💧', d:55  },
      { n:'f12', img:12, jp:'メノクラゲ',   fr:'Tentacool',     en:'Tentacool',    r:'common',   t:'💧', d:72  },
      { n:'f13', img:13, jp:'ドククラゲ',   fr:'Tentacruel',    en:'Tentacruel',   r:'uncommon', t:'💧', d:73  },
      { n:'f14', img:14, jp:'シェルダー',   fr:'Kokiyas',       en:'Shellder',     r:'common',   t:'💧', d:90  },
      { n:'f15', img:15, jp:'パルシェン',   fr:'Crustabri',     en:'Cloyster',     r:'uncommon', t:'💧', d:91  },
      { n:'f16', img:16, jp:'クラブ',       fr:'Krabby',        en:'Krabby',       r:'common',   t:'💧', d:98  },
      { n:'f17', img:17, jp:'キングラー',   fr:'Krabboss',      en:'Kingler',      r:'uncommon', t:'💧', d:99  },
      { n:'f18', img:18, jp:'タッツー',     fr:'Hypotrempe',    en:'Horsea',       r:'common',   t:'💧', d:116 },
      { n:'f19', img:19, jp:'シードラ',     fr:'Hypocéan',      en:'Seadra',       r:'uncommon', t:'💧', d:117 },
      { n:'f20', img:20, jp:'ラプラス',     fr:'Lokhlass',      en:'Lapras',       r:'rare',     t:'💧', d:131 },
      { n:'f21', img:21, jp:'オムナイト',   fr:'Amonita',       en:'Omanyte',      r:'common',   t:'💧', d:138 },
      { n:'f22', img:22, jp:'オムスター',   fr:'Amonistar',     en:'Omastar',      r:'uncommon', t:'💧', d:139 },
      { n:'f23', img:23, jp:'フリーザー',   fr:'Artikodin',     en:'Articuno',     r:'holo',     t:'❄️', d:144 },
      { n:'f24', img:24, jp:'ライチュウ',   fr:'Raichu',        en:'Raichu',       r:'holo',     t:'⚡', d:26  },
      { n:'f25', img:25, jp:'レアコイル',   fr:'Magneton',      en:'Magneton',     r:'holo',     t:'⚡', d:82  },
      { n:'f26', img:26, jp:'ザップドス',   fr:'Electhor',      en:'Zapdos',       r:'holo',     t:'⚡', d:145 },
      { n:'f27', img:27, jp:'ヤドン',       fr:'Ramoloss',      en:'Slowpoke',     r:'common',   t:'💧', d:79  },
      { n:'f28', img:28, jp:'ヤドラン',     fr:'Flagadoss',     en:'Slowbro',      r:'uncommon', t:'💧', d:80  },
      { n:'f29', img:29, jp:'ゴース',       fr:'Fantominus',    en:'Gastly',       r:'common',   t:'👻', d:92  },
      { n:'f30', img:30, jp:'ゴースト',     fr:'Spectrum',      en:'Haunter',      r:'uncommon', t:'👻', d:93  },
      { n:'f31', img:31, jp:'ゲンガー',     fr:'Ectoplasma',    en:'Gengar',       r:'holo',     t:'👻', d:94  },
      { n:'f32', img:32, jp:'スリーパー',   fr:'Hypnomade',     en:'Hypno',        r:'holo',     t:'🔮', d:97  },
      { n:'f33', img:33, jp:'ミュウ',       fr:'Mew',           en:'Mew',          r:'holo',     t:'🔮', d:151 },
      { n:'f34', img:34, jp:'サンドパン',   fr:'Sablaireau',    en:'Sandslash',    r:'uncommon', t:'💀', d:28  },
      { n:'f35', img:35, jp:'イシツブテ',   fr:'Racaillou',     en:'Geodude',      r:'common',   t:'🪨', d:74  },
      { n:'f36', img:36, jp:'ゴローン',     fr:'Gravalanch',    en:'Graveler',     r:'uncommon', t:'🪨', d:75  },
      { n:'f37', img:37, jp:'ゴローニャ',   fr:'Grolem',        en:'Golem',        r:'holo',     t:'🪨', d:76  },
      { n:'f38', img:38, jp:'サワムラー',   fr:'Kicklee',       en:'Hitmonlee',    r:'holo',     t:'👊', d:106 },
      { n:'f39', img:39, jp:'カブト',       fr:'Kabuto',        en:'Kabuto',       r:'common',   t:'💧', d:140 },
      { n:'f40', img:40, jp:'カブトプス',   fr:'Kabutops',      en:'Kabutops',     r:'holo',     t:'💧', d:141 },
      { n:'f41', img:41, jp:'プテラ',       fr:'Ptéra',         en:'Aerodactyl',   r:'holo',     t:'🐉', d:142 },
      { n:'f42', img:42, jp:'メタモン',     fr:'Métamorph',     en:'Ditto',        r:'holo',     t:'⬛', d:132 },
      { n:'f43', img:43, jp:'カイリュー',   fr:'Dracolosse',    en:'Dragonite',    r:'holo',     t:'🐉', d:149 },
      // ── Trainers ──
      { n:'f44', img:44, jp:'エネルギーさがし', fr:"Recherche d'Énergie",  en:'Energy Search',     r:'common',   t:'🃏', item:'energy-powder' },
      { n:'f45', img:45, jp:'ギャンブラー',     fr:'Joueur',               en:'Gambler',           r:'common',   t:'🃏', item:'coin'          },
      { n:'f46', img:46, jp:'ふしぎなかせき',   fr:'Mystérieux Fossile',   en:'Mysterious Fossil', r:'common',   t:'🃏', item:'root-fossil'   },
      { n:'f47', img:47, jp:'リサイクル',       fr:'Recyclage',            en:'Recycle',           r:'uncommon', t:'🃏', item:'recycle'       },
      { n:'f48', img:48, jp:'フジオじいさん',   fr:'M. Fuji',              en:'Mr. Fuji',          r:'rare',     t:'🃏', item:'big-nugget'    },
    ],
  },

  /* ================================================================
     OR4 — ROCKET GANG — ロケット団 1997
     65 cartes — ordre exact checklist pokecardex
  ================================================================ */
  rocket: {
    name: { fr: 'ROCKET', en: 'ROCKET', jp: 'ロケット団' },
    subtitle: 'ロケット団 1997',
    cdnSet: 'OR4',
    cards: [
      { n:'r01', img:1,  jp:'アーボ',             fr:'Abo',                   en:'Ekans',               r:'common',   t:'☁️', d:23  },
      { n:'r02', img:2,  jp:'Drk アーボック',     fr:'Arbok Obscur',          en:'Dark Arbok',          r:'holo',     t:'☁️', d:24  },
      { n:'r03', img:3,  jp:'ズバット',           fr:'Nosferapti',            en:'Zubat',               r:'common',   t:'☁️', d:41  },
      { n:'r04', img:4,  jp:'Drk ゴルバット',     fr:'Nosféralto Obscur',     en:'Dark Golbat',         r:'uncommon', t:'☁️', d:42  },
      { n:'r05', img:5,  jp:'ナゾノクサ',         fr:'Mystherbe',             en:'Oddish',              r:'common',   t:'🌿', d:43  },
      { n:'r06', img:6,  jp:'Drk クサイハナ',     fr:'Ortide Obscur',         en:'Dark Gloom',          r:'uncommon', t:'🌿', d:44  },
      { n:'r07', img:7,  jp:'Drk ラフレシア',     fr:'Rafflesia Obscur',      en:'Dark Vileplume',      r:'holo',     t:'🌸', d:45  },
      { n:'r08', img:8,  jp:'ベトベター',         fr:'Tadmorv',               en:'Grimer',              r:'common',   t:'☁️', d:88  },
      { n:'r09', img:9,  jp:'Drk ベトベトン',     fr:'Grotadmorv Obscur',     en:'Dark Muk',            r:'rare',     t:'☁️', d:89  },
      { n:'r10', img:10, jp:'ドガース',           fr:'Smogo',                 en:'Koffing',             r:'common',   t:'☁️', d:109 },
      { n:'r11', img:11, jp:'Drk マタドガス',     fr:'Smogogo Obscur',        en:'Dark Weezing',        r:'holo',     t:'☁️', d:110 },
      { n:'r12', img:12, jp:'ヒトカゲ',           fr:'Salamèche',             en:'Charmander',          r:'common',   t:'🔥', d:4   },
      { n:'r13', img:13, jp:'Drk リザード',       fr:'Reptincel Obscur',      en:'Dark Charmeleon',     r:'uncommon', t:'🔥', d:5   },
      { n:'r14', img:14, jp:'Drk リザードン',     fr:'Dracaufeu Obscur',      en:'Dark Charizard',      r:'holo',     t:'🔥', d:6   },
      { n:'r15', img:15, jp:'ポニータ',           fr:'Ponyta',                en:'Ponyta',              r:'common',   t:'🔥', d:77  },
      { n:'r16', img:16, jp:'Drk ギャロップ',     fr:'Galopa Obscur',         en:'Dark Rapidash',       r:'uncommon', t:'🔥', d:78  },
      { n:'r17', img:17, jp:'Drk ブースター',     fr:'Pyroli Obscur',         en:'Dark Flareon',        r:'rare',     t:'🔥', d:136 },
      { n:'r18', img:18, jp:'ゼニガメ',           fr:'Carapuce',              en:'Squirtle',            r:'common',   t:'💧', d:7   },
      { n:'r19', img:19, jp:'Drk カメール',       fr:'Carabaffe Obscur',      en:'Dark Wartortle',      r:'uncommon', t:'💧', d:8   },
      { n:'r20', img:20, jp:'Drk カメックス',     fr:'Tortank Obscur',        en:'Dark Blastoise',      r:'holo',     t:'💧', d:9   },
      { n:'r21', img:21, jp:'コダック',           fr:'Psykokwak',             en:'Psyduck',             r:'common',   t:'💧', d:54  },
      { n:'r22', img:22, jp:'Drk ゴルダック',     fr:'Akwakwak Obscur',       en:'Dark Golduck',        r:'uncommon', t:'💧', d:55  },
      { n:'r23', img:23, jp:'コイキング',         fr:'Magicarpe',             en:'Magikarp',            r:'common',   t:'💧', d:129 },
      { n:'r24', img:24, jp:'Drk ギャラドス',     fr:'Léviator Obscur',       en:'Dark Gyarados',       r:'holo',     t:'💧', d:130 },
      { n:'r25', img:25, jp:'Drk シャワーズ',     fr:'Aquali Obscur',         en:'Dark Vaporeon',       r:'rare',     t:'💧', d:134 },
      { n:'r26', img:26, jp:'コイル',             fr:'Magnéti',               en:'Magnemite',           r:'common',   t:'⚡', d:81  },
      { n:'r27', img:27, jp:'Drk レアコイル',     fr:'Magneton Obscur',       en:'Dark Magneton',       r:'holo',     t:'⚡', d:82  },
      { n:'r28', img:28, jp:'ビリリダマ',         fr:'Voltorbe',              en:'Voltorb',             r:'common',   t:'⚡', d:100 },
      { n:'r29', img:29, jp:'Drk マルマイン',     fr:'Électrode Obscur',      en:'Dark Electrode',      r:'uncommon', t:'⚡', d:101 },
      { n:'r30', img:30, jp:'Drk ライチュウ',     fr:'Voltali Obscur',        en:'Dark Jolteon',        r:'rare',     t:'⚡', d:135 },
      { n:'r31', img:31, jp:'ケーシィ',           fr:'Abra',                  en:'Abra',                r:'common',   t:'🔮', d:63  },
      { n:'r32', img:32, jp:'Drk フーディン',     fr:'Kadabra Obscur',        en:'Dark Kadabra',        r:'uncommon', t:'🔮', d:64  },
      { n:'r33', img:33, jp:'Drk アラカザム',     fr:'Alakazam Obscur',       en:'Dark Alakazam',       r:'holo',     t:'🔮', d:65  },
      { n:'r34', img:34, jp:'ヤドン',             fr:'Ramoloss',              en:'Slowpoke',            r:'common',   t:'💧', d:79  },
      { n:'r35', img:35, jp:'Drk ヤドラン',       fr:'Flagadoss Obscur',      en:'Dark Slowbro',        r:'rare',     t:'💧', d:80  },
      { n:'r36', img:36, jp:'スリープ',           fr:'Soporifik',             en:'Drowzee',             r:'common',   t:'🔮', d:96  },
      { n:'r37', img:37, jp:'Drk スリーパー',     fr:'Hypnomade Obscur',      en:'Dark Hypno',          r:'holo',     t:'🔮', d:97  },
      { n:'r38', img:38, jp:'ディグダ',           fr:'Taupiqueur',            en:'Diglett',             r:'common',   t:'💀', d:50  },
      { n:'r39', img:39, jp:'Drk ダグトリオ',     fr:'Triopikeur Obscur',     en:'Dark Dugtrio',        r:'rare',     t:'💀', d:51  },
      { n:'r40', img:40, jp:'マンキー',           fr:'Férosinge',             en:'Mankey',              r:'common',   t:'👊', d:56  },
      { n:'r41', img:41, jp:'Drk オコリザル',     fr:'Colossinge Obscur',     en:'Dark Primeape',       r:'uncommon', t:'👊', d:57  },
      { n:'r42', img:42, jp:'ワンリキー',         fr:'Machoc',                en:'Machop',              r:'common',   t:'👊', d:66  },
      { n:'r43', img:43, jp:'Drk ゴーリキー',     fr:'Machopeur Obscur',      en:'Dark Machoke',        r:'uncommon', t:'👊', d:67  },
      { n:'r44', img:44, jp:'Drk カイリキー',     fr:'Mackogneur Obscur',     en:'Dark Machamp',        r:'holo',     t:'👊', d:68  },
      { n:'r45', img:45, jp:'コラッタ',           fr:'Rattata',               en:'Rattata',             r:'common',   t:'⬛', d:19  },
      { n:'r46', img:46, jp:'Drk ラッタ',         fr:'Rattatac Obscur',       en:'Dark Raticate',       r:'uncommon', t:'⬛', d:20  },
      { n:'r47', img:47, jp:'ニャース',           fr:'Miaouss',               en:'Meowth',              r:'common',   t:'⬛', d:52  },
      { n:'r48', img:48, jp:'Drk ペルシアン',     fr:'Persian Obscur',        en:'Dark Persian',        r:'holo',     t:'⬛', d:53  },
      { n:'r49', img:49, jp:'イーブイ',           fr:'Evoli',                 en:'Eevee',               r:'common',   t:'⬛', d:133 },
      { n:'r50', img:50, jp:'ポリゴン',           fr:'Porygon',               en:'Porygon',             r:'uncommon', t:'💻', d:137 },
      { n:'r51', img:51, jp:'ミニリュウ',         fr:'Minidraco',             en:'Dratini',             r:'common',   t:'🐉', d:147 },
      { n:'r52', img:52, jp:'Drk ハクリュー',     fr:'Draco Obscur',          en:'Dark Dragonair',      r:'uncommon', t:'🐉', d:148 },
      { n:'r53', img:53, jp:'Drk カイリュー',     fr:'Dracolosse Obscur',     en:'Dark Dragonite',      r:'holo',     t:'🐉', d:149 },
      // ── Trainers ──
      { n:'r54', img:54, jp:'ねむれ！',               fr:'Bonne nuit, les petits !',          en:'Sleep!',                  r:'common',   t:'🃏', item:'cheri-berry'   },
      { n:'r55', img:55, jp:'あなをほる',              fr:'Excavatrice',                       en:'Digger',                  r:'common',   t:'🃏', item:'ground-gem'    },
      { n:'r56', img:56, jp:'ガス爆発',               fr:'Attaque au gaz gluant',             en:'Goop Gas Attack',         r:'common',   t:'🃏', item:'poison-barb'   },
      { n:'r57', img:57, jp:'夜の廃品回収',            fr:'Raid nocturne dans les poubelles',  en:'Nightly Garbage Run',     r:'uncommon', t:'🃏', item:'black-glasses' },
      { n:'r58', img:58, jp:'勝負だ！',               fr:'Défi !',                            en:'Challenge!',              r:'uncommon', t:'🃏', item:'amulet-coin'   },
      { n:'r59', img:59, jp:'にせオーキドのリベンジ',  fr:"La revanche de Chen, l'imposteur",  en:"Imposter Oak's Revenge",  r:'uncommon', t:'🃏', item:'red-flute'     },
      { n:'r60', img:60, jp:'サカキの命令',            fr:'A la façon du Boss',                en:"The Boss's Way",          r:'rare',     t:'🃏', item:'dark-gem'      },
      { n:'r61', img:61, jp:'ロケット団のアジト',      fr:'Attaque sournoise des Rocket',      en:"Rocket's Sneak Attack",   r:'rare',     t:'🃏', item:'smoke-ball'    },
      { n:'r62', img:62, jp:'ロケット団参上！',        fr:'Et voilà la Team Rocket !',         en:'Here Comes Team Rocket!', r:'holo',     t:'🃏', item:'dusk-ball'     },
      // ── Special Energies ──
      { n:'r63', img:63, jp:'ポーションエネルギー',    fr:'Énergie Potion',                    en:'Potion Energy',           r:'common',   t:'⚡', item:'potion'        },
      { n:'r64', img:64, jp:'全快エネルギー',          fr:'Énergie Guérisseuse',               en:'Full Heal Energy',        r:'common',   t:'⚡', item:'full-heal'     },
      { n:'r65', img:65, jp:'Drk ライチュウ',          fr:'Énergie Multicolore',               en:'Dark Raichu',             r:'holo',     t:'⚡', d:26                 },
    ],
  },
};

const EXTRA_TYPES = {
  fr: [
    { emoji: '🌿', label: 'Plante'   }, { emoji: '🔥', label: 'Feu'      },
    { emoji: '💧', label: 'Eau'      }, { emoji: '⚡', label: 'Foudre'   },
    { emoji: '🔮', label: 'Psy'      }, { emoji: '✊', label: 'Combat'   },
    { emoji: '⭐', label: 'Incolore' }, { emoji: '💀', label: 'Poison'   },
    { emoji: '🃏', label: 'Trainer'  }, { emoji: '🌀', label: 'Energie'  },
  ],
  en: [
    { emoji: '🌿', label: 'Grass'     }, { emoji: '🔥', label: 'Fire'      },
    { emoji: '💧', label: 'Water'     }, { emoji: '⚡', label: 'Lightning' },
    { emoji: '🔮', label: 'Psychic'   }, { emoji: '✊', label: 'Fighting'  },
    { emoji: '⭐', label: 'Colorless' }, { emoji: '💀', label: 'Poison'    },
    { emoji: '🃏', label: 'Trainer'   }, { emoji: '🌀', label: 'Energy'    },
  ],
  jp: [
    { emoji: '🌿', label: 'くさ'      }, { emoji: '🔥', label: 'ほのお'    },
    { emoji: '💧', label: 'みず'      }, { emoji: '⚡', label: 'でんき'    },
    { emoji: '🔮', label: 'エスパー'  }, { emoji: '✊', label: 'かくとう'  },
    { emoji: '⭐', label: 'むしょく'  }, { emoji: '💀', label: 'どく'      },
    { emoji: '🃏', label: 'トレーナー'}, { emoji: '🌀', label: 'エネルギー'},
  ],
};
